### ISSUE TITLE
Query regarding the send_sip_register()

### ISSUE THREAD

**Issue by ns-pananda** [SythilTech/Python-SIP#1]
Hi Steve,

How are you? I was building a simple SIP client and stumbled upon your library. I went through the code and found that in the register method, you are getting a register_address parameter, which is not referenced anywhere in the code. 

`def send_sip_register(self, register_address, register_frequency=3600)`

Could you please let me know whether you have updated version of the code? Also if you have any sample script that uses this library, could you please upload the same here. Thanks!

-Andy

**Comment by SythilTech** [comment]
Yes this does appear to be a design oversight as the parameter serves no purpose, I'll have to revisit the design of this at some point.

You can find the latest version inside my Odoo voip module
https://github.com/SythilTech/Odoo/blob/10.0/voip_sip_webrtc/models/sip.py

It is also has a python 3 equivalent inside the Odoo 11 version
https://github.com/SythilTech/Odoo/blob/11.0/voip_sip_webrtc/models/sip.py

You can see the module in use primarily inside the voip_account.py file, it serves to setup automated calls so that it can stream a pre recorded audio file.
https://github.com/SythilTech/Odoo/blob/10.0/voip_sip_webrtc/models/voip_account.py#L328

**Comment by ns-pananda** [comment]
Hey, thanks for sharing the details. I will take a look at the other scripts.
